stages:
  - build
  - unit tests

build:
  stage: build
  script:
    - dotnet build CdekSdk.sln
    - dotnet pack -c Release CdekSdk.sln
  artifacts:
    paths:
      - CdekApi\bin\Release\*.nupkg
      - CdekApi\bin\Release\*.snupkg

unit_tests:
  stage: unit tests
  before_script:
    - echo "Normal build -- running unit tests..."
    - chcp 65001
    # uncomment to install the required tools --
    # dotnet tool install -g trx2junit
  script:
    # building again the solution
    - dotnet test CdekSdk.sln --logger "trx;LogFileName=TestResults.trx"
    - trx2junit CdekApi.Tests\TestResults\TestResults.trx
  artifacts:
    paths:
      - CdekApi.Tests\TestResults\TestResults.trx
    reports:
      junit:
        - CdekApi.Tests\TestResults\TestResults.xml
    expire_in: 1 day
