stages:
  - build
  - unit tests
  - publish

build:
  stage: build
  script:
    - dotnet build CdekSdk.sln

unit_tests:
  stage: unit tests
  before_script:
    - echo "Normal build -- running unit tests..."
    - chcp 65001
    # uncomment to install the required tools --
    # dotnet tool install -g trx2junit
  script:
    # building again the solution
    - dotnet test CdekSdk.sln --logger "trx;LogFileName=TestResults.trx"
  after_script:
    - echo Converting test results
    - trx2junit CdekSdk.Tests\TestResults\TestResults.trx
  artifacts:
    paths:
      - CdekSdk.Tests\TestResults\TestResults.trx
    reports:
      junit:
        - CdekSdk.Tests\TestResults\TestResults.xml
    expire_in: 1 day

publish:
  stage: publish
  script:
    - dotnet pack -c Release CdekSdk.sln
  artifacts:
    paths:
      - CdekSdk\bin\Release\*.nupkg
      - CdekSdk\bin\Release\*.snupkg
