name: Publish to Nuget

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore 

    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal

    - name: Pack
      run: dotnet pack -c Release --no-build -p:PublicRelease=true

    - name: Publish
      run: dotnet nuget push CdekSdk/bin/Release/CdekSdk*.nupkg -k "${{ secrets.NUGET_CDEK_SDK_API_TOKEN }}" -s https://api.nuget.org/v3/index.json
